"""initial

Revision ID: 857c209ff6ab
Revises: 
Create Date: 2026-05-19 20:10:54.701031

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('tmdb_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('letterboxd_slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tmdb_type', sa.String(length=16), nullable=False),
    sa.Column('letterboxd_avg_rating', sa.Float(), nullable=True),
    sa.Column('last_resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_films_letterboxd_slug'), ['letterboxd_slug'], unique=True)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('list', 'watchlist', 'films', 'rss', 'discovery', 'rotation', name='scrape_source_enum'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', 'running', name='scrape_status_enum'), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index('ix_scrape_runs_source_started', ['source', 'started_at'], unique=False)
        batch_op.create_index('ix_scrape_runs_target', ['target_id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letterboxd_username', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_letterboxd_username'), ['letterboxd_username'], unique=True)

    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('list', 'watchlist', name='source_type_enum'), nullable=False),
    sa.Column('letterboxd_list_id', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('film_count', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.Enum('never', 'success', 'error', name='sync_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letterboxd_list_id', name='uq_lists_letterboxd_id'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_lists_user_slug')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_user_id'), ['user_id'], unique=False)

    op.create_table('viewing_logs',
    sa.Column('letterboxd_guid', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('watched_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('member_like', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('letterboxd_guid')
    )
    with op.batch_alter_table('viewing_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viewing_logs_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewing_logs_user_id'), ['user_id'], unique=False)

    op.create_table('watched_films',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_seen_watched_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_watched_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('rss', 'films-page', name='watched_source_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tmdb_id')
    )
    with op.batch_alter_table('watched_films', schema=None) as batch_op:
        batch_op.create_index('ix_watched_films_tmdb', ['tmdb_id'], unique=False)

    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('pending_removal_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['films.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'tmdb_id')
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index('ix_list_items_list_position', ['list_id', 'position'], unique=False)
        batch_op.create_index('ix_list_items_tmdb', ['tmdb_id'], unique=False)

    op.create_table('sublists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_list_id', sa.Integer(), nullable=True),
    sa.Column('parent_combined_kind', sa.Enum('union', 'intersection', 'union-unwatched', name='combined_kind_enum'), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_items', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Enum('letterboxd', 'random', 'reverse', name='sort_order_enum'), nullable=False),
    sa.Column('min_rating', sa.Float(), nullable=True),
    sa.Column('max_rating', sa.Float(), nullable=True),
    sa.Column('min_year', sa.Integer(), nullable=True),
    sa.Column('max_year', sa.Integer(), nullable=True),
    sa.Column('added_after', sa.DateTime(), nullable=True),
    sa.Column('added_before', sa.DateTime(), nullable=True),
    sa.Column('rotation_enabled', sa.Boolean(), nullable=False),
    sa.Column('rotation_interval', sa.Interval(), nullable=True),
    sa.Column('rotation_batch_size', sa.Integer(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(parent_list_id IS NOT NULL AND parent_combined_kind IS NULL) OR (parent_list_id IS NULL AND parent_combined_kind IS NOT NULL)', name='ck_sublists_parent_exclusive'),
    sa.ForeignKeyConstraint(['parent_list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sublists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sublists_parent_list_id'), ['parent_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sublists_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_sublists_combined_slug', ['parent_combined_kind', 'slug'], unique=True, sqlite_where=sa.text('parent_combined_kind IS NOT NULL'))
        batch_op.create_index('uq_sublists_user_slug', ['user_id', 'slug'], unique=True, sqlite_where=sa.text('user_id IS NOT NULL'))

    op.create_table('sublist_items',
    sa.Column('sublist_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('served_since', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sublist_id'], ['sublists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['films.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sublist_id', 'tmdb_id')
    )
    with op.batch_alter_table('sublist_items', schema=None) as batch_op:
        batch_op.create_index('ix_sublist_items_served_since', ['sublist_id', 'served_since'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sublist_items', schema=None) as batch_op:
        batch_op.drop_index('ix_sublist_items_served_since')

    op.drop_table('sublist_items')
    with op.batch_alter_table('sublists', schema=None) as batch_op:
        batch_op.drop_index('uq_sublists_user_slug', sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index('uq_sublists_combined_slug', sqlite_where=sa.text('parent_combined_kind IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_sublists_user_id'))
        batch_op.drop_index(batch_op.f('ix_sublists_parent_list_id'))

    op.drop_table('sublists')
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index('ix_list_items_tmdb')
        batch_op.drop_index('ix_list_items_list_position')

    op.drop_table('list_items')
    with op.batch_alter_table('watched_films', schema=None) as batch_op:
        batch_op.drop_index('ix_watched_films_tmdb')

    op.drop_table('watched_films')
    with op.batch_alter_table('viewing_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viewing_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_viewing_logs_tmdb_id'))

    op.drop_table('viewing_logs')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_user_id'))

    op.drop_table('lists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_letterboxd_username'))

    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scrape_runs_target')
        batch_op.drop_index('ix_scrape_runs_source_started')

    op.drop_table('scrape_runs')
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_films_letterboxd_slug'))

    op.drop_table('films')
    # ### end Alembic commands ###
