"""settings per entity

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-20 15:21:34.140336

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lists_incremental_interval', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('lists_full_interval', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('flap_confirm_scrapes', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rss_interval', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('watchlist_incremental_interval', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('watchlist_full_interval', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('films_backstop_interval', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('discovery_interval', sa.Interval(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('discovery_interval')
        batch_op.drop_column('films_backstop_interval')
        batch_op.drop_column('watchlist_full_interval')
        batch_op.drop_column('watchlist_incremental_interval')
        batch_op.drop_column('rss_interval')

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_column('flap_confirm_scrapes')
        batch_op.drop_column('lists_full_interval')
        batch_op.drop_column('lists_incremental_interval')

    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
